export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const DELETE_DONE = 'delete_DONE'
export const UPDATE_ALL_TODOS = 'update_all_todos'
export const RECEIVE_TODOS = 'receive_todos'
